{{- if .Values.global.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace | default "xflow" }}
  labels:
    {{- include "xflow.labels" . | nindent 4 }}
{{- end }}
