# Backend ServiceAccount with IRSA (IAM Roles for Service Accounts)
# Created by: eksctl create iamserviceaccount --cluster=xflow-cluster --namespace=default --name=backend-sa --attach-policy-arn=arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess --approve
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::134059028370:role/eksctl-xflow-cluster-addon-iamserviceaccount--Role1-VcpbdbiD8GJi
  labels:
    app.kubernetes.io/managed-by: eksctl
