{{- if and .Values.spark.enabled .Values.spark.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.spark.namespace | default "spark-jobs" }}
  labels:
    {{- include "xflow.labels" . | nindent 4 }}
{{- end }}
