{{- if .Values.spark.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
  namespace: {{ .Values.spark.namespace | default "spark-jobs" }}
  labels:
    app: spark
    {{- include "xflow.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "persistentvolumeclaims"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-rolebinding
  namespace: {{ .Values.spark.namespace | default "spark-jobs" }}
  labels:
    app: spark
    {{- include "xflow.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.spark.serviceAccount.name | default "spark-sa" }}
    namespace: {{ .Values.spark.namespace | default "spark-jobs" }}
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
