{{- if and .Values.spark.enabled .Values.spark.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.spark.serviceAccount.name | default "spark-sa" }}
  namespace: {{ .Values.spark.namespace | default "spark-jobs" }}
  labels:
    app: spark
    {{- include "xflow.labels" . | nindent 4 }}
  {{- with .Values.spark.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
