apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: xflow

resources:
  - namespace.yaml
  - mongodb/secret.yaml
  - mongodb/pvc.yaml
  - mongodb/statefulset.yaml
  - mongodb/service.yaml
  - backend/secret.yaml
  - backend/configmap.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - opensearch/pvc.yaml
  - opensearch/statefulset.yaml
  - opensearch/service.yaml
  - opensearch/dashboards-deployment.yaml
  - opensearch/dashboards-service.yaml
  - opensearch/ingress.yaml
