{{- if .Values.mongodb.enabled }}
{{- if not .Values.mongodb.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    app: mongodb
    {{- include "xflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.auth.rootUsername | default "root" | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.auth.rootPassword | default "changeme" | quote }}
{{- end }}
{{- end }}
