{{- if and .Values.opensearch.enabled .Values.opensearch.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-pvc
  labels:
    app: opensearch
    {{- include "xflow.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.opensearch.persistence.storageClass | default (include "xflow.storageClass" .) }}
  resources:
    requests:
      storage: {{ .Values.opensearch.persistence.size | default "10Gi" }}
{{- end }}
