{{- if and .Values.monitoring.grafana.enabled (not .Values.monitoring.grafana.admin.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: {{ .Values.monitoring.namespace | default "monitoring" }}
  labels:
    app: grafana
    {{- include "xflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.monitoring.grafana.admin.userKey | default "admin-user" }}: {{ .Values.monitoring.grafana.admin.user | default "admin" | quote }}
  {{ .Values.monitoring.grafana.admin.passwordKey | default "admin-password" }}: {{ .Values.monitoring.grafana.admin.password | default "changeme" | quote }}
{{- end }}
